export const categories = [
  { id: "all", name: "כל המתוקים" },
  { id: "boys-birthday", name: "עוגות יום הולדת בנים" },
  { id: "girls-birthday", name: "עוגות יום הולדת בנות" },
  { id: "adults-birthday", name: "עוגות יום הולדת מבוגרים" },
  { id: "brit", name: "עוגות לברית/בריתה" },
  { id: "smash-cake", name: "סמאש קייק" },
  { id: "bachelor", name: "עוגות למסיבת רווקים/רווקות" },
  { id: "anniversary", name: "עוגות ליום נישואין" },
  { id: "army", name: "עוגות למסיבת גיוס/שחרור" },
  { id: "chocolate-eggs", name: "ביצי שוקולד" },
  { id: "cupcakes", name: "קאפקייקס" },
  { id: "bar-mitzvah", name: "עוגות בר מצווה" },
  { id: "bat-mitzvah", name: "עוגות בת מצווה" },
  { id: "wedding", name: "עוגות חתונה" },
  { id: "rosh-hashana", name: "עוגות לראש השנה" },
  { id: "valentines", name: "עוגות ליום האהבה" },
  { id: "shavuot", name: "עוגות לשבועות" },
  { id: "other", name: "שונות" },
  { id: "gift-boxes", name: "מארזים מתוקים" },
]

export interface Cake {
  id: string
  name: string
  category: string
  categoryName: string
  description: string
  imageUrl: string
}

// Sample cakes data - in a real app, this would come from a database
export const cakes: Cake[] = [
  {
    id: "1",
    name: "עוגת ספיידרמן",
    category: "boys-birthday",
    categoryName: "עוגות יום הולדת בנים",
    description: "עוגת יום הולדת מרשימה בעיצוב ספיידרמן עם דמות תלת מימדית",
    imageUrl: "/placeholder-cakes/cake-1.jpg",
  },
  {
    id: "2",
    name: "עוגת נסיכות",
    category: "girls-birthday",
    categoryName: "עוגות יום הולדת בנות",
    description: "עוגת נסיכות קסומה עם כתר זהב ופרחים מסוכר",
    imageUrl: "/placeholder-cakes/cake-2.jpg",
  },
  {
    id: "3",
    name: "עוגת יום הולדת 50",
    category: "adults-birthday",
    categoryName: "עוגות יום הולדת מבוגרים",
    description: "עוגת יום הולדת אלגנטית למבוגרים עם עיצוב זהב ושחור",
    imageUrl: "/placeholder-cakes/cake-3.jpg",
  },
  {
    id: "4",
    name: "עוגת ברית מילה",
    category: "brit",
    categoryName: "עוגות לברית/בריתה",
    description: "עוגה מתוקה לברית עם עיצוב תינוקי בגוונים תכלת ולבן",
    imageUrl: "/placeholder-cakes/cake-4.jpg",
  },
  {
    id: "5",
    name: "סמאש קייק ורוד",
    category: "smash-cake",
    categoryName: "סמאש קייק",
    description: "סמאש קייק מושלם לצילומי יום הולדת שנה",
    imageUrl: "/placeholder-cakes/cake-5.jpg",
  },
  {
    id: "6",
    name: "עוגת רווקות",
    category: "bachelor",
    categoryName: "עוגות למסיבת רווקים/רווקות",
    description: "עוגה שובבה ומיוחדת למסיבת רווקות",
    imageUrl: "/placeholder-cakes/cake-6.jpg",
  },
  {
    id: "7",
    name: "עוגת יום נישואין",
    category: "anniversary",
    categoryName: "עוגות ליום נישואין",
    description: "עוגה רומנטית לחגיגת יום נישואין",
    imageUrl: "/placeholder-cakes/cake-7.jpg",
  },
  {
    id: "8",
    name: "עוגת גיוס",
    category: "army",
    categoryName: "עוגות למסיבת גיוס/שחרור",
    description: "עוגה מרשימה לחגיגת גיוס עם סמלים צבאיים",
    imageUrl: "/placeholder-cakes/cake-8.jpg",
  },
  {
    id: "9",
    name: "ביצי שוקולד מעוצבות",
    category: "chocolate-eggs",
    categoryName: "ביצי שוקולד",
    description: "ביצי שוקולד בעיצוב אישי מלאות בהפתעות",
    imageUrl: "/placeholder-cakes/cake-9.jpg",
  },
  {
    id: "10",
    name: "קאפקייקס פרחים",
    category: "cupcakes",
    categoryName: "קאפקייקס",
    description: "קאפקייקס מעוטרים בפרחי קרם צבעוניים",
    imageUrl: "/placeholder-cakes/cake-10.jpg",
  },
  {
    id: "11",
    name: "עוגת בר מצווה",
    category: "bar-mitzvah",
    categoryName: "עוגות בר מצווה",
    description: "עוגת בר מצווה מרשימה עם עיצוב תפילין וספר תורה",
    imageUrl: "/placeholder-cakes/cake-11.jpg",
  },
  {
    id: "12",
    name: "עוגת בת מצווה",
    category: "bat-mitzvah",
    categoryName: "עוגות בת מצווה",
    description: "עוגת בת מצווה יפיפייה בגוונים ורודים וזהב",
    imageUrl: "/placeholder-cakes/cake-12.jpg",
  },
  {
    id: "13",
    name: "עוגת חתונה קלאסית",
    category: "wedding",
    categoryName: "עוגות חתונה",
    description: "עוגת חתונה רב-קומתית עם פרחים טבעיים",
    imageUrl: "/placeholder-cakes/cake-13.jpg",
  },
  {
    id: "14",
    name: "עוגת ראש השנה",
    category: "rosh-hashana",
    categoryName: "עוגות לראש השנה",
    description: "עוגת שנה טובה עם עיצוב תפוח בדבש ורימונים",
    imageUrl: "/placeholder-cakes/cake-14.jpg",
  },
  {
    id: "15",
    name: "עוגת לבבות",
    category: "valentines",
    categoryName: "עוגות ליום האהבה",
    description: "עוגה רומנטית ליום האהבה עם לבבות אדומים",
    imageUrl: "/placeholder-cakes/cake-15.jpg",
  },
  {
    id: "16",
    name: "עוגת שבועות",
    category: "shavuot",
    categoryName: "עוגות לשבועות",
    description: "עוגת גבינה מעוצבת לחג השבועות",
    imageUrl: "/placeholder-cakes/cake-16.jpg",
  },
  {
    id: "17",
    name: "עוגה מיוחדת",
    category: "other",
    categoryName: "שונות",
    description: "עוגה בעיצוב מיוחד לפי הזמנה",
    imageUrl: "/placeholder-cakes/cake-17.jpg",
  },
  {
    id: "18",
    name: "מארז מתוק",
    category: "gift-boxes",
    categoryName: "מארזים מתוקים",
    description: "מארז מתנה מתוק עם מגוון פינוקים",
    imageUrl: "/placeholder-cakes/cake-18.jpg",
  },
]
